version: '3.5'

services:
  dockerize:
    image: jwilder/dockerize
    command: sh

  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    tmpfs:
      - /var/lib/postgresql/data
