version: '3.5'

services:
  dockerize:
    image: jwilder/dockerize
    command: sh

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    tmpfs:
      - /var/lib/mysql

  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - 5432:5432
    tmpfs:
      - /var/lib/postgresql/data
